"""Added tags and other product related items

Revision ID: b8a81efbb210
Revises: 0ee53e63cd68
Create Date: 2022-07-27 18:00:24.463720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a81efbb210'
down_revision = '0ee53e63cd68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('purchases', sa.BigInteger(), nullable=False))
    op.add_column('products', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'created')
    op.drop_column('products', 'purchases')
    op.drop_column('products', 'tags')
    # ### end Alembic commands ###
